import { useState } from "react";
import { ListContext } from "./ListContext";

export function ListProvider({ children }) {
  const [list, setList] = useState([
    {
      id: 1,
      name: "Pizza",
      category: "Dinner",
      prepTime: 40,
      difficulty: 2,
      healthy: false,
      favourite: true,
      timesCooked: 0,
      lastCooked: null,
    },
    {
      id: 2,
      name: "Lasagne",
      category: "Dinner",
      prepTime: 90,
      difficulty: 5,
      healthy: false,
      favourite: true,
      timesCooked: 0,
      lastCooked: null,
    },
    {
      id: 3,
      name: "Pasta",
      category: "Dinner",
      prepTime: 60,
      difficulty: 3,
      healthy: true,
      favourite: false,
      timesCooked: 0,
      lastCooked: null,
    },
    {
      id: 4,
      name: "Avocado Toast",
      category: "Breakfast",
      prepTime: 10,
      difficulty: 1,
      healthy: true,
      favourite: true,
      timesCooked: 14,
      lastCooked: "2026-07-22",
    },
    {
      id: 5,
      name: "Caesar Salad",
      category: "Lunch",
      prepTime: 15,
      difficulty: 1,
      healthy: true,
      favourite: false,
      timesCooked: 5,
      lastCooked: "2026-06-18",
    },
    {
      id: 6,
      name: "Berry Acai Bowl",
      category: "Breakfast",
      prepTime: 12,
      difficulty: 2,
      healthy: true,
      favourite: false,
      timesCooked: 0,
      lastCooked: null,
    },
    {
      id: 7,
      name: "Beef Stir Fry",
      category: "Dinner",
      prepTime: 25,
      difficulty: 3,
      healthy: true,
      favourite: true,
      timesCooked: 8,
      lastCooked: "2026-07-10",
    },
    {
      id: 8,
      name: "Chocolate Brownies",
      category: "Dessert",
      prepTime: 45,
      difficulty: 2,
      healthy: false,
      favourite: true,
      timesCooked: 3,
      lastCooked: "2026-05-02",
    },
    {
      id: 9,
      name: "Club Sandwich",
      category: "Lunch",
      prepTime: 20,
      difficulty: 2,
      healthy: false,
      favourite: false,
      timesCooked: 2,
      lastCooked: "2026-07-01",
    },
    {
      id: 10,
      name: "Miso Ramen",
      category: "Dinner",
      prepTime: 120,
      difficulty: 4,
      healthy: false,
      favourite: true,
      timesCooked: 1,
      lastCooked: "2026-01-15",
    },
  ]);

  return (
    <ListContext.Provider value={{ list, setList }}>
      {children}
    </ListContext.Provider>
  );
}
